/* eslint-disable */
/* prettier-ignore */
// biome-ignore format: off
// biome-ignore lint: off
// @ts-nocheck
// Generated by unplugin-svg-component
declare module '~virtual/svg-component' {
  const SvgIcon: import("vue").DefineComponent<{
      name: {
          type: import("vue").PropType<"access" | "bug" | "config" | "dashboard" | "file-excel" | "file-file" | "file-img" | "file-mp3" | "file-pdf" | "file-ppt" | "file-txt" | "file-video" | "file-word" | "file" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "lesson-discuss" | "lesson-live" | "lesson-text" | "lesson-video" | "lesson-work" | "link" | "load" | "lock" | "menu-activity" | "menu-banner" | "menu-chat" | "menu-class" | "menu-community" | "menu-course" | "menu-document" | "menu-feedback" | "menu-home" | "menu-member" | "menu-note" | "menu-notification" | "menu-organization" | "menu-settings" | "menu" | "monitor" | "network" | "note" | "plus" | "search" | "setting">;
          default: string;
          required: true;
      };
  }, {}, unknown, {}, {}, import("vue").ComponentOptionsMixin, import("vue").ComponentOptionsMixin, {}, string, import("vue").VNodeProps & import("vue").AllowedComponentProps & import("vue").ComponentCustomProps, Readonly<import("vue").ExtractPropTypes<{
      name: {
          type: import("vue").PropType<"access" | "bug" | "config" | "dashboard" | "file-excel" | "file-file" | "file-img" | "file-mp3" | "file-pdf" | "file-ppt" | "file-txt" | "file-video" | "file-word" | "file" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "lesson-discuss" | "lesson-live" | "lesson-text" | "lesson-video" | "lesson-work" | "link" | "load" | "lock" | "menu-activity" | "menu-banner" | "menu-chat" | "menu-class" | "menu-community" | "menu-course" | "menu-document" | "menu-feedback" | "menu-home" | "menu-member" | "menu-note" | "menu-notification" | "menu-organization" | "menu-settings" | "menu" | "monitor" | "network" | "note" | "plus" | "search" | "setting">;
          default: string;
          required: true;
      };
  }>>, {
      name: "access" | "bug" | "config" | "dashboard" | "file-excel" | "file-file" | "file-img" | "file-mp3" | "file-pdf" | "file-ppt" | "file-txt" | "file-video" | "file-word" | "file" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "lesson-discuss" | "lesson-live" | "lesson-text" | "lesson-video" | "lesson-work" | "link" | "load" | "lock" | "menu-activity" | "menu-banner" | "menu-chat" | "menu-class" | "menu-community" | "menu-course" | "menu-document" | "menu-feedback" | "menu-home" | "menu-member" | "menu-note" | "menu-notification" | "menu-organization" | "menu-settings" | "menu" | "monitor" | "network" | "note" | "plus" | "search" | "setting";
  }>;
  export const svgNames: ["access", "bug", "config", "dashboard", "file-excel", "file-file", "file-img", "file-mp3", "file-pdf", "file-ppt", "file-txt", "file-video", "file-word", "file", "fullscreen-exit", "fullscreen", "keyboard-down", "keyboard-enter", "keyboard-esc", "keyboard-up", "lesson-discuss", "lesson-live", "lesson-text", "lesson-video", "lesson-work", "link", "load", "lock", "menu-activity", "menu-banner", "menu-chat", "menu-class", "menu-community", "menu-course", "menu-document", "menu-feedback", "menu-home", "menu-member", "menu-note", "menu-notification", "menu-organization", "menu-settings", "menu", "monitor", "network", "note", "plus", "search", "setting"];
  export type SvgName = "access" | "bug" | "config" | "dashboard" | "file-excel" | "file-file" | "file-img" | "file-mp3" | "file-pdf" | "file-ppt" | "file-txt" | "file-video" | "file-word" | "file" | "fullscreen-exit" | "fullscreen" | "keyboard-down" | "keyboard-enter" | "keyboard-esc" | "keyboard-up" | "lesson-discuss" | "lesson-live" | "lesson-text" | "lesson-video" | "lesson-work" | "link" | "load" | "lock" | "menu-activity" | "menu-banner" | "menu-chat" | "menu-class" | "menu-community" | "menu-course" | "menu-document" | "menu-feedback" | "menu-home" | "menu-member" | "menu-note" | "menu-notification" | "menu-organization" | "menu-settings" | "menu" | "monitor" | "network" | "note" | "plus" | "search" | "setting";
  export default SvgIcon;
}
